Improved UI + Code refactoring

diff --git a/SOURCES/7zcat b/SOURCES/7zcat
--- a/SOURCES/7zcat
+++ b/SOURCES/7zcat
@@ -10,7 +10,7 @@ fi
 ########################################################################################
 
 APP="7zcat"
-VER="1.3.5"
+VER="1.4.0"
 
 ########################################################################################
 
@@ -52,6 +52,11 @@ SHORT_ARGS="p:password F:!fast nc:!no_colors h:!help v:!version"
 
 ########################################################################################
 
+prompt="› "
+masksym="${CL_DARK}•${CL_NORM}"
+
+########################################################################################
+
 main() {
   if [[ ! -t 1 || -n "$no_colors" ]] ; then
     unset NORM BOLD UNLN RED GREEN YELLOW BLUE MAG CYAN GREY DARK
@@ -70,9 +75,11 @@ main() {
   fi
 
   if ! type -P 7za &>/dev/null ; then
-    error "Error! 7zip not installed." $RED
+    error "Error! 7zip not installed."
     exit 1
   fi
+
+  configureUI
 
   [[ -n "$pass" ]] && password="$pass"
   [[ "$password" == "true" ]] && readUserPassword
@@ -89,15 +96,15 @@ main() {
     file_name=$(basename "$file")
 
     if [[ ! -f $file ]] ; then
-      error "Error! ${CL_BL_RED}${file_name}${CL_RED} is not a file." $RED
+      error "Error! ${CL_BL_RED}${file_name}${CL_RED} is not a file."
       continue
     elif [[ ! -r $file ]]; then
-      error "Error! ${CL_BL_RED}${file_name}${CL_RED} is not a readable file." $RED
+      error "Error! ${CL_BL_RED}${file_name}${CL_RED} is not a readable file."
       continue
     fi
 
     if ! is7zArch "$file" ; then
-      error "Error! ${CL_BL_RED}${file_name}${CL_RED} is not a 7z archive." $RED
+      error "Error! ${CL_BL_RED}${file_name}${CL_RED} is not a 7z archive."
       continue
     fi
 
@@ -110,7 +117,7 @@ main() {
       7za e -p"${password}" $options "$file" 2> /dev/null
 
       if [[ $? -eq 2 ]] ; then
-        error "Error! Wrong password." $RED
+        error "Error! Wrong password."
         has_errors=true
       fi
     else
@@ -121,6 +128,17 @@ main() {
 
   if [[ -n "$has_errors" ]] ; then
     exit 1
+  fi
+}
+
+# Configure user interface
+#
+# Code: No
+# Echo: No
+configureUI() {
+  if ! printenv | grep 'LANG' | grep -qi 'UTF-8' ; then
+    prompt="> "
+    masksym="*"
   fi
 }
 
@@ -142,14 +160,14 @@ readUserPassword() {
       show "Please enter password:" $CYAN
     fi
 
-    read -re -p "> " user_pass
+    read -re -p "${prompt}" user_pass
 
-    clnPassInput ${#user_pass}
+    maskPassword ${#user_pass}
 
     show ""
 
     if [[ -z "$user_pass" ]] ; then
-      error "Password can't be empty" $YELLOW
+      warn "Password can't be empty"
     else
       password="$user_pass"
       break
@@ -184,15 +202,17 @@ isProtectedArch() {
 
 # Replace entered password by masking symbols
 #
+# 1: Password length (Number)
+#
 # Code: No
 # Echo: No
-clnPassInput() {
+maskPassword() {
   local i result
 
-  result="${result}> "
+  result="${result}${prompt}"
 
   for i in $(seq 1 "$1") ; do
-    result="${result}*"
+    result="${result}${masksym}"
   done
 
   printf "\e[1A%s\n" "$result"
@@ -223,7 +243,17 @@ show() {
 # Code: No
 # Echo: No
 error() {
-  show "$@" 1>&2
+  show "$*" $RED 1>&2
+}
+
+# Shows warning message
+#
+# 1: Message (String)
+#
+# Code: No
+# Echo: No
+warn() {
+  show "$*" $BROWN 1>&2
 }
 
 # Print usage info
@@ -280,7 +310,7 @@ about() {
 # Code: No
 # Echo: No
 showArgWarn() {
-  error "Unknown argument $1" $RED
+  error "Unknown argument $1"
   exit 1
 }
 
